openapi: 3.0.0
info:
  title: Your API Title
  description: Companies House test API.
  version: 1.0.0
servers:
  - url: "http://localhost:80"

paths:
  /endpoint:
    httpMethod:
      summary: Retrieve data
      description: Retrieve data from the API.
      parameters:
        - name: limit
          in: query
          description: The maximum number of items to return
          required: false
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string